easy_admin:
    entities:
        Node:
            class: App\Entity\Node
            label: 'Products'
            list:
                fields: ['title','description','price']
                title: 'List of products'
            form:
                fields: ['title','description']