easy_admin:
    entities:
      Node:
        class: App\Entity\Node
        label: 'Products'
        show:
          fields: ['id', 'title', 'description', 'price', 'categories']
        list:
          title: 'List of products'
          fields:
          - { property: 'firstImageName', type: 'image', template: 'image_in_list.html.twig'}
          - { property: 'id' }
          - { property: 'title' }
          - { property: 'price' }
          - { property: 'description' }
          actions:
           - { name: 'show', label: '', icon: 'search' }
           - { name: 'edit', label: '', icon: 'edit' }
           - { name: 'delete', label: '', icon: 'trash' }
        form:
          fields:
            - { type: 'tab' , label: 'Basic Information' }
            - { property: 'title', type: 'App\Form\Type\LocaleKeyValueType'}
            - { property: 'description', type: 'App\Form\Type\LocaleKeyValueType'}
            - { property: 'categories', type: 'easyadmin_autocomplete', type_options:{multiple: true, class: 'App\Entity\Category'}}
            - { type: 'tab' , label: 'Attributes' }
            - { property: 'attributes', type: 'App\Form\Type\NodeAttributesType'}
            - { type: 'tab' , label: 'Attachments' }
            - { property: 'attachments', type: 'collection', type_options:{ entry_type: 'App\Form\Type\AttachmentImageType', by_reference: false}}
      Category:
        class: App\Entity\Category
        label: 'Categories'
        list:
          title: 'List of Categories'
          actions:
            - { name: 'show', label: '', icon: 'search' }
            - { name: 'edit', label: '', icon: 'edit' }
            - { name: 'delete', label: '', icon: 'trash' }
          fields: ['id', 'title']
        show:
          fields: ['id', 'title', 'parent']
        form:
          fields:
          - { property: 'title', label: 'Title', type: 'App\Form\Type\LocaleKeyValueType' }
          - { property: 'parent', type: 'easyadmin_autocomplete', label: 'Parent category' }
      Attribute:
         class: App\Entity\Attribute
         label: 'Attributes'
         form:
           fields:
            - 'name'
            - { property: 'data_type', type: 'choice', type_options: {required: true, choices: {'Text': 'string', 'Number': 'integer', 'Floating point number': 'numeric' }}}
            - { property: 'input_type', type: 'choice', type_options: {required: true, choices: {'Text': 'text', 'Multi text': 'multiText','Select': 'select', 'Multi select': 'multiSelect'}}}
            - { property: 'is_active', type: 'checkbox'}
            - { property: 'values', type_options: {'disabled': true}}
         edit:
          fields:
             - { property: 'name', type_options: {'disabled': true}}
             - { property: 'data_type', type_options: {'disabled': true}}
             - { property: 'input_type', type_options: {'disabled': true}}
      AttributeValue:
         class: App\Entity\AttributeValue
         label: 'Attribute Values'
         list:
          fields: ['id', 'value', 'attribute']
         form:
           fields: ['value', 'attribute']
