easy_admin:
    entities:
      Node:
        class: App\Entity\Node
        label: 'Products'
        list:
          title: 'List of products'
          fields: ['id', 'title', 'description', 'price']
          actions:
           - { name: 'show', label: '', icon: 'search' }
           - { name: 'edit', label: '', icon: 'edit' }
           - { name: 'delete', label: '', icon: 'trash' }
        form:
          fields:
            - { property: 'title', type: 'App\Form\Type\LocaleKeyValueType'}
            - { property: 'description', type: 'App\Form\Type\LocaleKeyValueType'}
            - { property: 'categories', type: 'easyadmin_autocomplete', type_options:{multiple: true, class: 'App\Entity\Category'}}

      Category:
        class: App\Entity\Category
        label: 'Categories'
        list:
          title: 'List of Categories'
          actions:
            - { name: 'show', label: '', icon: 'search' }
            - { name: 'edit', label: '', icon: 'edit' }
            - { name: 'delete', label: '', icon: 'trash' }
          fields: ['id', 'title']
        show:
          fields: ['id', 'title', 'parent']
        form:
          fields:
          - { property: 'title', label: 'Title', type: 'App\Form\Type\LocaleKeyValueType' }
          - { property: 'parent', type: 'easyadmin_autocomplete', label: 'Parent category' }