fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: "%mailer_user_address%"
        sender_name: "%mailer_user_name%"
    registration:
        confirmation:
            enabled:    false # change to true for required email confirmation
        form:
            type: App\Form\RegistrationFormType