security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        api:
            pattern:    ^/api
            fos_oauth:  true
            stateless:  true
            anonymous:  true
        main:
            pattern: ^/
            user_checker: security.user_checker
            form_login:
                check_path: /_security/login_check
                login_path: /_security/login
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                default_target_path: /admin/
            logout:
                path: /_security/logout
            anonymous:    true


    access_control:
        - { path: ^/admin/, role: ROLE_ADMIN }