# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'
    mailer_user_address: 'admin@admin.com'
    mailer_user_name: 'admin'
    front_host: '%env(FRONT_HOST)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    7cart.deserializer:
        alias: App\Service\Deserializer
        public: true
    7cart.serializer:
        alias: App\Service\Serializer
        public: true
    7cart.helper:
        alias: App\Service\Helper
        public: true

    json_exception_listener:
        class: App\EventListener\JsonExceptionListener
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException, priority: 200 }

    7cart.fos_customized_mailer:
        class: App\Service\FOSCustomizedMailer
        bind:
          $frontHost: '%front_host%'
        public: true
        autowire: true
        autoconfigure: false
        parent: 'fos_user.mailer'

    App\Controller\TokenController:
        public: true
        arguments:
            - '@fos_oauth_server.server'

    App\Controller\Api\V1\UserController:
        public: true
        arguments:
            $formRegistrationFactory: '@fos_user.registration.form.factory'
            $formResettingFactory: '@fos_user.resetting.form.factory'
            $tokenGenerator: '@fos_user.util.token_generator'
            $mailer: '@7cart.fos_customized_mailer'
